### ISSUE TITLE
rule with leading tab ignored, leading spaces (or no whitespace) required

### ISSUE THREAD

**Issue by GaryShelden** [def-gthill/lexurgy#18]
Reading your comments on previous white-space issue, I think this bug report is moot

Rule Syntax:

```
<rule-name>:
    <old-sounds> => <new-sounds> / <environment>
```
The rule is ignored if the white-space before <old-sounds> is a tab.

This is inconvenient for coders like me, who instinctively use a tab to indent a line. If course this only applies to rule files prepared externally, as in the UI online, one cannot imbed tabs.

The attached file w-avardic-v2.lsc.txt contains the rule:
[w-avardic-v2-bugs.lsc.txt](https://github.com/def-gthill/lexurgy/files/5611054/w-avardic-v2-bugs.lsc.txt)
```
final-d-loss:
	d => * / _ $
```
If the white-space before the "d" is a tab, the rule is ignored.

The word-list:
ʔabʔid
ʔabʔa
grunʔid
grunan
ʔaiʔid
ʔaiʔuid
ʔaiʔiad
ʔaiid
ʔaiud

produces, with d-loss rule with a tab:
ʔabʔid  => háp'id
ʔabʔa   => háp'a
grunʔid => grundid
grunan
ʔaiʔid  => hétid
ʔaiʔuid => hékwid
ʔaiʔiad => hétyad
ʔaiid   => héd
ʔaiud   => háyud

but produces, with d-loss rule with spaces:
ʔabʔid  => háp'i
ʔabʔa   => háp'a
grunʔid => grundi
grunan
ʔaiʔid  => héti
ʔaiʔuid => hékwi
ʔaiʔiad => hétya
ʔaiid   => hé
ʔaiud   => háyu

**Comment by def-gthill** [comment]
This is fixed in commit 1c5a4434e69f166c86c7b3325f4aadd8d06dd9e6 and will be included in the next release.

I'm an indent with spaces person myself, so thanks for bringing to my attention that tabs didn't work.
