### ISSUE TITLE
unexpected and unexplained results

### ISSUE THREAD

**Issue by GaryShelden** [def-gthill/lexurgy#19]
Using these three files:

[w-avardic-v2-bugs.lsc.txt](https://github.com/def-gthill/lexurgy/files/5612545/w-avardic-v2-bugs.lsc.txt)
[w-avardic.wli.txt](https://github.com/def-gthill/lexurgy/files/5612546/w-avardic.wli.txt)
[w-avardic_ev.wli.txt](https://github.com/def-gthill/lexurgy/files/5612547/w-avardic_ev.wli.txt)

As the _ev.wli file shows, the middle section (2 of 3) of forms produces forms with only some of the sound changes performed. specifically, the rule "glottal-resolution" has not been applied. _ev.wli shows the forms expected.

It should be noted that .wli.txt is an extract of a longer .wli with many similar forms, which are changed as expected, the attached .wli.txt shows only the forms immediately before and immediately after the problematic forms.

I have not used any "hungry" wild-cards except in "stress-application", so I don't believe this is the issue. I am mystified by the failure occurring on only 9 forms out of 27 (and 9 forms out of the original 117)

**Comment by def-gthill** [comment]
The forms that aren't working have question marks in them instead of glottal stops (ma?id instead of maʔid). When I replace the question marks with glottal stops, I get closer to your expected forms.

**Comment by GaryShelden** [comment]
Sh*t! I shoulda known. Thanks!
