### ISSUE TITLE
ease of use: two-to-one curly bracket subrules

### ISSUE THREAD

**Issue by AdamantConlanger** [def-gthill/lexurgy#23]
say I want to do:
`demonstrational-rule-one:`
` a {e, o} => {e e, o o}`
Then I have to say
`demonstrational-rule-one:`
` {a e, a o} => {e e, o o}`
lest it give me a "1 left, 2 right" error.
This isn't a major issue, but it did take me a while to figure out the first time around. It's not the most intuitive thing.
I do understand, however, that it might be hard to implement, seeing as the section inside the bracket is the thing the parser's trying to compare. I'd completely understand if this is unrealistic to attempt. In that case, it might be a good idea to mention this quirkiness in the documentation.

**Comment by def-gthill** [comment]
I actually expect the parsing wouldn't be too difficult for this; I've already done something like this for rules like `{e, i}&[unstressed] => {ə, ɨ}`, where Lexurgy will automatically treat this as a shortcut for `{e&[unstressed], i&[unstressed]} => {ə, ɨ}`. I'm worried that there might be ambiguity (or at least unintuitive behaviour), but I can look into implementing this.

**Comment by def-gthill** [comment]
This is implemented in commit c868c2f7353596c1257ab1e050bb8775231b7637 and will be included in the next release.
