### ISSUE TITLE
intermediate romanization character counting.

### ISSUE THREAD

**Issue by AdamantConlanger** [def-gthill/lexurgy#24]
let's say we have a file

`Feature Vowelheight(open, openmid, mid, closemid, close)`
`Feature Vowelfrontness(front, central, back)`
`Feature Vowelrounding(*unrounded, rounded)`
`Feature Syllabicity(syllabic, static)`
`Feature Voicing(*voiced, unvoiced)`
`Feature Consonantplace(bilabial, alveolar)`
`Feature Consonantmanner(nasal, plosive)`
``
`Symbol i [syllabic close front]`
`Symbol u [syllabic close back rounded]`
`Symbol a [syllabic open central]`
`Symbol m̩ [syllabic bilabial nasal]`
`Symbol m [static bilabial nasal]`
`Symbol t [static unvoiced alveolar plosive]`
`Symbol b [static bilabial plosive]`
``
`demonstrational-rule-minus-one:`
` b => m / _ $`
``
`Romanizer-one:`
` unchanged`
``
`demonstrational-rule-zero:`
` [syllabic] [nasal] => * [syllabic]`
``
`Romanizer-two:`
` unchanged`
``
`demonstrational-rule-one:`
` t => * / _ $`

and we input

`ait`
`utib`

then you'll see that, in the output, the "=>" symbols don't line up. This is, again, because of there being a combining diacritic there. It really doesn't matter, but, for documentation's sake, I'll say it anyway.

**Comment by def-gthill** [comment]
Indeed, this is because the way I detect combining diacritics doesn't always work. I could easily provide a modifier that lets you tell Lexurgy that a diacritic is combining, or that a symbol contains a combining diacritic.

**Comment by def-gthill** [comment]
This is fixed in commit 897a9dd57138d8ef20e5ffa43c8ac0fea52db101, at least in new enough browsers, and the fix is live on the web app.
(My god, I spent at least 20 minutes using _Internet Explorer_ to get it just leaving the arrows ragged, rather than crashing completely. That's something I wish I could un-experience!)
