### ISSUE TITLE
Combining diacritics detach after sound changes.

### ISSUE THREAD

**Issue by creed2868** [def-gthill/lexurgy#25]
When I ran a sound change like this [front mid vowel] => [central mid vowel] that affected a vowel with a tone diacritic already applied, e.g. é, the tone diacritic becomes detached from the vowel. For example, é => ə ́. This does affect sound changes down the line.

**Comment by def-gthill** [comment]
Hmm, I'm not seeing this. I tried the following sound changes:

```
Feature type(*consonant, vowel)
Feature height(low, mid, high)
Feature frontness(front, central, back)
Feature +hightone
Diacritic ́  [+hightone]
Symbol e [mid front vowel]
Symbol ə [mid central vowel]

centering:
 [front mid vowel] => [central mid vowel]
```

And the results looked as expected, with the tone diacritic on top of the schwa. (See screenshot.)

![image](https://user-images.githubusercontent.com/5505409/109447558-30f74700-7a01-11eb-998d-b7e829241048.png)

Can you try these exact changes and see if you get the same result?

**Comment by creed2868** [comment]
Thank you, I figured out that it's just a problem with my computer displaying it.
