### ISSUE TITLE
Two optional characters in a row doesn't work

### ISSUE THREAD

**Issue by LingEarth** [def-gthill/lexurgy#27]
Given the following change:
```
Class cons {p, t, k}

raise-a:
    a => e / i @cons? @cons? _
```
These words change as follows:
```
ia    => ie
ika   => ike
ikta  => ikta
iktpa => iktpa
```
I would expect the first three to change, but only the first two do.

**Comment by def-gthill** [comment]
Thanks! I'm aware of this issue and have a fix in the repository (commit 9bfddfb9ae2fe03eb5a981b38aa0499b05f34007), I just need to release a new version with these changes. I should have time this weekend to get the release out.
