### ISSUE TITLE
Several error messages from the Sample Declarations preset

### ISSUE THREAD

**Issue by derkasbr** [def-gthill/lexurgy#30]
"The feature value "rounded" is not defined"
This seems to be caused by a missing '+' in one symbol (Symbol ɒ [vowel back **rounded** open])

After that:
"The feature value "high" is not defined"
This seems to be caused by the Diphthongs referencing vowel height, which is defined in the beginning as 'Open' through 'Close', and doesn't define 'high' in any way.

After that:
"The feature value "labial" is not defined"
Which  seems to be caused by 'Symbol ⱱ̟ [+voiced **labial** tap]', which... I'm unfamiliar with this symbol, but I think it's meant to say 'bilabial'.

After that:
"The feature value "fricative" is not defined"
Several symbols regarding several Lateral Fricatives are defined as 'fricative', whereas (I think) they're meant to say nonSibilantFricative or something. (i.e. 'Symbol ɬ [-voiced alveolar +lateral **fricative**]'

That's all that I noticed.

**Comment by def-gthill** [comment]
Good catch! This is being caught by the new consistency checks that make sure all feature values are defined before they're used. This example was never correct, it just silently didn't work instead of giving error messages.

I've fixed the errors and uploaded the new version to the web app.
