### ISSUE TITLE
Intervocallic loss of /ɣ/ is not working

### ISSUE THREAD

**Issue by ChineseKid** [def-gthill/lexurgy#34]
When I used this: `ɣ => * / [vowel] _ [vowel]` to remove /ɣ/ intervocalically, it doesn't work.
What I wanted: `eɣa => ea`
The result: `eɣa => eɣa`

**Comment by def-gthill** [comment]
Have you declared `a` and `e` to have the `vowel` feature?

**Comment by def-gthill** [comment]
Any updates on this?

**Comment by def-gthill** [comment]
Closing due to lack of information
