### ISSUE TITLE
not allowing syllable boundaries in output

### ISSUE THREAD

**Issue by Thomas-Patterson** [def-gthill/lexurgy#37]
I use syllable boundaries in my rules, why can't I have it use them in the output of them?

**Comment by def-gthill** [comment]
Are you using manual syllable boundaries you've coded yourself, or the new built-in support for syllable boundaries?

**Comment by def-gthill** [comment]
This is fixed in commit fa1a03c27081daba12bb1ba3d27425d453fbc9ee and will be included in the next release.
