### ISSUE TITLE
Suggestion: Make it possible to define classes from features

### ISSUE THREAD

**Issue by sievertst** [def-gthill/lexurgy#39]
For example, I would like to define the following:

```
# (current produces an error saying that "[" makes no sense in this context)
Class sonorant {[vowel], [nasal], [lateral], [approximant]}
```

Or are there any other elegant ways to do this that I haven’t thought of?

**Comment by def-gthill** [comment]
As far as I know there isn't currently an elegant way to do this, but a few are on my to-do list. Thanks for requesting.

**Comment by def-gthill** [comment]
Finally got to this one! Sorry it took so long...

Classes are still the same as always, but there's a [new type of declaration](https://www.meamoria.com/lexurgy/html/sc-tutorial.html#reusable-elements) that's much more flexible, and allows things like what you requested.

Thanks again for the suggestion!
