### ISSUE TITLE
Captures don't work through syllable breaks

### ISSUE THREAD

**Issue by AdamantConlanger** [def-gthill/lexurgy#40]
Say I have the input word
`to.o`
with explicit Syllables.
And I want to apply
`[]$1 $1 => [+long] *`
then it doesn't work. I just get the same in as out.

**Comment by def-gthill** [comment]
Thanks, I've reproduced the bug. I'm in the middle of fixing some other syllable-related bugs, so I'll add this one into the mix.

**Comment by AdamantConlanger** [comment]
I also noticed it's not possible to actually delete syllable boundaries, and you can't use a "* => . / ..." rule either. This could really get in the way.

**Comment by def-gthill** [comment]
I have tests set up for this problem too. Working on fixes.

**Comment by def-gthill** [comment]
Both of these are fixed in commit eedfcbb00cb8fdae733bdcf6c2bdd37f1cd8f4f6 and will be included in the next release.
