### ISSUE TITLE
Syllable features disappearing when using filter

### ISSUE THREAD

**Issue by Mardikhouran** [def-gthill/lexurgy#44]
With these sound changes:
```Feature (syllable) +stress

Diacritic ˈ (before) [+stress]

Class vowel {a, i, u}
Class cons {p, t, k, x}

Syllables:
 @cons? @vowel @cons?

stress-assignement:
 <syl> => [+stress] / _ <syl> $

swapping @vowel:
 u a => a u
```
And these words:
```
katak
kuta
pakit
kutuka
akakti
```
We get:
```
ˈka.tak
ka.tu
ˈpa.kit
ku.ta.ku
a.ˈkak.ti
```
However by rewriting `swapping` not to use a filter:
```
swapping:
 u [] a => a [] u
```
We get the expected results with the stress mark still present:
```
ˈka.tak
ˈka.tu
ˈpa.kit
ku.ˈta.ku
a.ˈkak.ti
```

**Comment by def-gthill** [comment]
This is fixed in commit 548803c0efc5d7d5caaeafeffba9f7d01765eaa8 and will be included in the next release (probably along with fixes to the other issues you reported, assuming they aren't as complicated to fix as this one was...)
