### ISSUE TITLE
Feature Suggestion: A rule that runs after each rule

### ISSUE THREAD

**Issue by bigyihsuan** [def-gthill/lexurgy#49]
I would like to be able to define a rule that runs after each rule is run.

I propose the `global` keyword, or some other keyword, that can modify a rule (like `propagate` or feature/class filters).

Consider the following example:
<pre>
insert-a:
    * => a / $ @C _

f-gem:
    @F$1 * => $1 $1 / @V _ @V

no-cc global:
    * => ə / @C _ @C
</pre>

The `no-cc` rule will run after each rule. So, a word like `ksen` becomes:
<pre>
ksen
(insert-a) => kasen
(no-cc)    => kasen    # no change because CC condition was not met
(f-gem)    => kassen
(no-cc)    => kasəsen
</pre>

Such a `global` rule could allow for constant features, such as a tonal language forcing tones on any new vowel that appears.

**Comment by def-gthill** [comment]
I like this idea. I can't promise when I'll get to it, but I've got it in the queue.

**Comment by def-gthill** [comment]
Lexurgy 1.1, released today, features "[cleanup rules](https://www.meamoria.com/lexurgy/html/sc-tutorial.html#cleanup-rules)" that do this. Thanks for the suggestion!
