### ISSUE TITLE
Feature Suggestion: Reusing rules

### ISSUE THREAD

**Issue by seaming** [def-gthill/lexurgy#51]
Hi!

Since Lexurgy rules are already all uniquely named and I often find myself in a situation where I want to re-apply a rule I used earlier, it seems natural to allow something like the following:
```
rule:
  a => b / _ b

rule # apply the rule `rule` again
```
To save copying and then also having to rename the rule that I'd already defined earlier.

I can foresee potential issues with the parsing here what with the flexibility around whitespace, so alternatively the re-run line could be introduced by a keyword, e.g. `run rule`, `apply rule`, etc.

Apologies if there's already a way of doing this that I've missed. Thanks!

**Comment by def-gthill** [comment]
I'm working on a similar feature for the version 1.1 release. Stay tuned!

**Comment by def-gthill** [comment]
Lexurgy 1.1 is now live, featuring "[deferred rules](https://www.meamoria.com/lexurgy/html/sc-tutorial.html#deferred-rules)" that can be used for situations like this.

Thanks for the suggestion!
