### ISSUE TITLE
Tracing shows wrong syllable boundaries

### ISSUE THREAD

**Issue by AdamantConlanger** [def-gthill/lexurgy#55]
Minimal example:
```
Syllables:
  C? V C?

rule:
  C => * / C _
```
Input: `VCCV`
Here, applying as usual works perfectly. But if you trace the input, the syllable boundaries haven't been updated yet.

**Comment by def-gthill** [comment]
I'd noticed this too, but hadn't gotten around to fixing it. Now seems like as good a time as any!

**Comment by def-gthill** [comment]
Fixed in commit 80c7896553c8fd97f3e0fc02df407fb8cf7e1ad8. Thanks to @neta-elad for contributing this fix!
