### ISSUE TITLE
Request: links from the cheat sheet to the tutorial

### ISSUE THREAD

**Issue by AdamantConlanger** [def-gthill/lexurgy#59]
Quite often, when referencing the cheat sheet, I need more information. As it is now, the only way to get to the corresponding section in the tutorial is by opening the tutorial and finding the subject in the ToC. It might be useful to have a links from the cheat sheet to the corresponding sections in the tutorial, just to make things easier.

**Comment by def-gthill** [comment]
This is implemented in the [new docs](https://lexurgy-app.vercel.app/sc/docs/cheatsheet).
