### ISSUE TITLE
(2/2) syllable boundary deletion causes stress loss of previous syllable

### ISSUE THREAD

**Issue by AdamantConlanger** [def-gthill/lexurgy#61]
(kinda) minimal example:
```
Feature type(consonant, vowel)
Feature (syllable) stress(*unstressed, stress)

Symbol t [consonant]
Symbol i [vowel]
Diacritic ˈ (before) (floating) [stress]

Syllables:
  explicit

#schwa-loss-errors:
#  [vowel] [consonant]? . [consonant] ə => [] [] * [] *

#schwa-loss-works-but-no-optional-consonant:
#  [vowel] . [consonant] ə => [] * [] *

schwa-loss-loses-stress:
  . [consonant] ə => * [] * / [vowel] [consonant]? _  # [consonant]? not required
```
input: `ˈi.tə.ti`
Running this removes the stress in the first syllable.

**Comment by def-gthill** [comment]
As of commit af5cfda0c640cceae3ad861a22985771984e064f, this particular example works. I had to completely rewrite the internal handling of syllable-level features though --- the existing system didn't preserve enough information to do reasonable things in every case. So I still want to test a few more interactions before I release this.
