### ISSUE TITLE
Trace improvements PR

### ISSUE THREAD

**Issue by neta-elad** [def-gthill/lexurgy#62]
Hey Graham,
I created a small PR https://github.com/def-gthill/lexurgy/pull/63 with a few trace improvements:

1. Fix a bug (I believe?) where traces were not saved when intermediates were off (they were still printed out).
2. Add the original traced word to each trace line: `Applied rule to word: before -> after`.
3. Add syllable rules to trace: `Applied syllables to word: before -> after`.

Let me know if there's anything you'd like me to change in the PR, or if you have any other ideas I might add to the trace while I'm at it.

Cheers

**Comment by def-gthill** [comment]
I'll leave any further comments on the PR itself.
