### ISSUE TITLE
Issues with Start-At and Anchored Steps (PR)

### ISSUE THREAD

**Issue by neta-elad** [def-gthill/lexurgy#65]
Hey Graham, not sure if you've seen: I sent a small PR about issues between anchored steps (syllabification rules, clean-ups) and passing the `start-at` flag to Lexurgy (https://github.com/def-gthill/lexurgy/pull/64).

**Comment by def-gthill** [comment]
Thanks, I'll take a look. But please don't open issues like this; conversation about a PR should go in comments on the PR itself.
