### ISSUE TITLE
Lexurgy Daemon / Server

### ISSUE THREAD

**Issue by neta-elad** [def-gthill/lexurgy#67]
Hey Graham, this is an idea I've been starting to play around with, but I wanted to discuss before I go any further beyond the prototype implementation I have now:

I'm working on a [tool](https://github.com/neta-elad/pyconlang) which is (among other things) an interactive environment to run Lexurgy. The use case is:
- Constant sound change file (it may change once in a while)
- Small queries (one word to a few at a time)
- "start at" / "stop before" may change for every query
- Tracing on / off for every query

I've noticed that running Lexurgy is a bit slow (even though running the sound changes themselves is pretty fast). 
I've attributed this to two factors:

1. Loading up the JVM
2. Parsing the sound change file

Both of these need not happen for every query, so I've been working on a "lexurgy server" mode,
which loads up a sound change file and then stays alive, waiting for queries from `stdin`.
I also have a hacky syntax, so that queries that start with `; after=<after>,before=<before>,tracing=<tracing>` will change the state of the server, so that the following queries will use these settings.

I don't think this is a great a system, but I was hoping to get some feedback from you,
if this sounds like something you would be willing to incorporate into Lexurgy.
(If you want to see the ugly, hacky code I have now, it's [here](https://github.com/def-gthill/lexurgy/blob/794f67cb153ac9f7fbfb62d94b199bd8d712d114/src/jvmMain/kotlin/com/meamoria/lexurgy/MainJvm.kt#L130).)

Thanks!

(N.B. this has nothing to do with the [PR](https://github.com/def-gthill/lexurgy/pull/66) I opened)

**Comment by def-gthill** [comment]
I ran into the same problem when I was working on a similar Python tool. I ended up doing a bunch of fancy processing to try to batch together as many Lexurgy calls as possible... for some reason it didn't occur to me to modify Lexurgy to run continuously like this!

So I like the idea; feel free to keep working on it and PR it when you're happy with it!
