### ISSUE TITLE
New lexurgy update times out when given large inputs

### ISSUE THREAD

**Issue by PyxelM** [def-gthill/lexurgy#73]
<img width="495" alt="Screenshot 2023-08-30 at 15 52 34" src="https://github.com/def-gthill/lexurgy/assets/79010057/2ee6cfb1-3a46-4547-b505-a3759e33fc24">

It didn't time out before, it would simply freeze for a while and eventually give the output. Would appreciate support for large inputs, such as entire lexicons, as this is what I do.

**Comment by def-gthill** [comment]
Sorry about this issue. I'm still figuring out how to make the new system work smoothly.

Can you tell me 1) how many words you're trying to put through at once, and 2) how long you had to wait for results with the old version? Remember that you can still access the [old version here](https://lexurgy-j4yvfxcce-def-gthill.vercel.app/sc).

**Comment by def-gthill** [comment]
Both the old and new UI now offer a full minute for a sound change run. This is about as much as the current architecture allows.
