### ISSUE TITLE
Lexurgy 1.3.3 on the CLI has to be killed manually

### ISSUE THREAD

**Issue by Mardikhouran** [def-gthill/lexurgy#74]
I have to terminate the process explicitly after the last input file has been written. This is especially tedious when using Lexurgy in a bash script acting on several sound change files in a row.

This only affects version 1.3.3.

**Comment by def-gthill** [comment]
Thanks for reporting. I'll look into it.

In the meantime, you aren't missing anything by downgrading to 1.3.2, which didn't add or fix anything relevant to the CLI.

**Comment by def-gthill** [comment]
Fixed in [1.3.5](https://github.com/def-gthill/lexurgy/releases/tag/v1.3.5)
