### ISSUE TITLE
Lexurgy CLI loops indefinitely

### ISSUE THREAD

**Issue by Wofi** [def-gthill/lexurgy#78]
Hello, when I try to run the Lexurgy CLI to apply sound changes, it loops until I close the cmd window or terminate with ctrl-c:
```
C:\Users\wofi\Desktop\lang>lexurgy sc changes.lsc words.wli

C:\Users\wofi\Desktop\lang>lexurgy sc changes.lsc words.wli

C:\Users\wofi\Desktop\lang>lexurgy sc changes.lsc words.wli

C:\Users\wofi\Desktop\lang>lexurgy sc changes.lsc words.wli

C:\Users\wofi\Desktop\lang>lexurgy sc changes.lsc words.wli
```
I am running windows 10. I have lexurgy installed into C:\Users\wofi\Desktop\tools\lexurgy\bin and added to my PATH.

The files passed into the program are as follows:

changes.lsc
```
rewrite:
 j => i
 then: ŭ => u
```

words.wli
```
Ĉiuj
```

Any help will be much appreciated!

**Comment by def-gthill** [comment]
Having trouble reproducing this. I tried it with CMD and PowerShell and GitBash, all on Windows 10. I also tried both giving the path to the executable explicitly and adding the bin directory to PATH. Everything worked as expected.

To confirm, did you see this with Lexurgy 1.6.0 or an earlier version?

**Comment by Wofi** [comment]
This is with 1.6.0. I've tried using both an Oracle version of Java 12 and a Zulu version of Java 8 (just what I had lying around) and I had the issue with both versions.

**Comment by def-gthill** [comment]
What shell are you using?

**Comment by Wofi** [comment]
The default windows cmd.exe, I don't think I've done anything weird to it. I get the same issue when I run the command using a .bat file.

**Comment by def-gthill** [comment]
What happens if you run `lexurgy --help`?

**Comment by Wofi** [comment]
Oh, I figured out what the issue was! I had a lexurgy.bat in the folder, so when I tried to run lexurgy, it was running the .bat, which then would try to run lexurgy.bat (instead of the lexurgy in the path), so it was looping forever. It seems to work fine now that I've renamed the .bat. My mistake! Thank you for the help!

**Comment by def-gthill** [comment]
Glad to hear you figured it out!
