### ISSUE TITLE
[New UI] Show cleanup rule name when cleaning up

### ISSUE THREAD

**Issue by bigyihsuan** [def-gthill/lexurgy#80]
I have multiple `cleanup` rules:

```
no-same-vowels cleanup:
[vowel]$1 $1 => [+long] *

penult-stress cleanup:
<syl>&[+stressed] => [-stressed] / $ _ $
<syl> => [+stressed] / _ <syl> $ // {[+stressed] <syl>* _, _ <syl>* [+stressed]}
```

However, in the rule trace, it does not say which cleanup rules are being used:

![image](https://github.com/def-gthill/lexurgy/assets/12767476/b4b1914c-4229-4335-a536-39b3fb8ac7bc)

I would like to be able to see which cleanup rule is being used here.

**Comment by def-gthill** [comment]
Added this. Thanks!
