### ISSUE TITLE
[New UI] Be able to resize text areas vertically

### ISSUE THREAD

**Issue by bigyihsuan** [def-gthill/lexurgy#81]
If you have inputs longer than 19 lines or so, it gains a scrollbar and becomes hard to view all at once.

For example, this is what the website looks like in my roughly 2560x1440 monitor:

![image](https://github.com/user-attachments/assets/aa13863a-433d-442d-9ab2-6d56c123ff7c)

Only about half the page is used by the actual tool, the rest is blank space.

I would like to be able to resize the app vertically so that I can fit the app to my screen size, and view my long inputs all at once.

**Comment by def-gthill** [comment]
As of [this commit](https://github.com/def-gthill/lexurgy-app/commit/95d083180881772dd95ef0ce76e55468a7a303f8), the app automatically expands to fill the window.
