### ISSUE TITLE
Diacritics being defined more than once in different spots

### ISSUE THREAD

**Issue by TealUmbrella** [def-gthill/lexurgy#84]
If I were to have a setup such as

```
Feature +aspirated
Feature +preaspirated

Diacritic ʰ (floating) [+aspirated]
Diacritic ʰ (before) [+preaspirated]
```

It would give me the error "The diacritic "ʰ" is defined more than once," even though it's put in a different place. 
I'd like to add preaspiration, but I can only do it using a different Unicode character.

**Comment by def-gthill** [comment]
This would lead to ambiguous parsing. Does `apʰpa` contain an aspirated stop followed by a plain stop, or a plain stop followed by a preaspirated stop?

As you say, please use a different Unicode character if you want both aspiration and preaspiration.
