### ISSUE TITLE
Symbols and digraphs in relation to successive changes and syllable boundaries

### ISSUE THREAD

**Issue by u3556490** [def-gthill/lexurgy#87]
Good day, thanks for making this incredible tool but lately I have run into some difficulties. I hope these are just user issues and some advice could be shared for me to rectify my change rules. I've tried my best to search for similar issues from the past but have had no avail.

To begin with, **"symbols" generated as a result of a previous change are not identified**. Please see the following minimal example ([link here](www.lexurgy.com/sc?changes=U3ltYm9sIGl1CgpydWxlMDoKYSA9PiBpCgpydWxlMToKe2l1LCBpd30gPT4ganUKCg&input=bWl1dApmYXU)):

```
Symbol iu

rule0:
a => i

rule1:
{iu, iw} => ju
```
> Note: I omitted the diacritic for non-syllabic symbols, but that does not affect our analysis.

With input `miut` it correctly changes it to `mjut` (by rule1), whereas with input `fau` it changes to `fiu` (rule0) but rule1 cannot match the `iu` sequence and leaves it as is. I surmise this is because, given symbols are considered one single element, the newly generated `iu` sequence is interpreted as two adjacent elements `i` and `u` instead of the expected single unit, hence the result.

An **imperfect workaround** is to drop the symbol declaration. It is imperfect for obvious reasons - symbols are used so that digraphs can be correctly matched within a syllable. In fact, the conlang I'm working on has explicit syllables and lexical stress, adding it to the mix we might have:

```
Feature (syllable) +stress
Diacritic ˈ (before) [+stress]
# Symbol iu, iw
Syllables:
  explicit

rule0:
a => i

rule1:
{iu, iw} => ju
```
> [link](www.lexurgy.com/sc?changes=RmVhdHVyZSAoc3lsbGFibGUpICtzdHJlc3MKRGlhY3JpdGljIMuIIChiZWZvcmUpIFsrc3RyZXNzXQpTeWxsYWJsZXM6CiAgZXhwbGljaXQKCiMgU3ltYm9sIGl1LCBpdwoKcnVsZTA6CmEgPT4gaQoKcnVsZTE6CntpdSwgaXd9ID0-IGp1Cgo&input=y4htaXV0CsuIZmF1CmRpLsuId2Fz)

It comes as no surprise that input `di.ˈwas` yields `dj.ˈuis`. Without the symbols to confine the digraph `iw` to be within the same syllable, the match occurs across syllable borders because syllables do not break adjacency. The rule `rule1` can be patched like this:

```
{iu, iw} => ju / _ .
```

But it still matches across syllables for `ti.u.la.ˈsi` which turns into `tj.u.li.ˈsi`. That is, the validity of the "patch" depends on the phonotactics of the conlang in question and thus it may not be a universal fix.

To this end, may I ask if **there is a way to temporarily make syllable boundaries break adjacency, or equivalently, a way to match the _absence_ of syllable breaks within a pattern**, without using symbols?

I hope I have put this clearly enough. Your help would be much appreciated!

**Comment by def-gthill** [comment]
> I surmise this is because, given symbols are considered one single element, the newly generated iu sequence is interpreted as two adjacent elements i and u instead of the expected single unit, hence the result.

This exactly. The fix is to add a rule to combine them:

```
Symbol iu

rule0:
a => i
then:
i u => iu

rule1:
{iu, iw} => ju
```

> To this end, may I ask if there is a way to temporarily make syllable boundaries break adjacency, or equivalently, a way to match the absence of syllable breaks within a pattern

There is, you can use `!.` to mean "only if there isn't a syllable break here":

```
Feature (syllable) +stress
Diacritic ˈ (before) [+stress]

Syllables:
  explicit

rule0:
a => i

rule1:
{i !. u, i !. w} => ju
```
